### ISSUE TITLE
Feature Request: Make it work with chalk-animation

### ISSUE THREAD

**Issue by nova93** [ajay-gandhi/asciify-image#14]
It would be great, if it was possible to animate ASCII art with https://github.com/bokub/chalk-animation.

```
const options = {
 color: false
}

asciify(fullPath, options).then(asciified => {
    logger.log(chalk.green(asciified));
    chalkAnimation.rainbow(asciified);
  });
```

**Comment by nova93** [comment]
It works nicely with https://github.com/bokub/gradient-string!

**Comment by ajay-gandhi** [comment]
Hi Robert, I'm open to the idea but a bit too busy to implement it myself right now. I'd be happy to look at a PR though!

**Comment by kodie** [comment]
This works fine for me:

```js
asciify('https://via.placeholder.com/1000x500/000000/FF0000?text=Loading...', {
  color: false,
  fit: 'box',
  width: '100%'
}, (err, text) => {
  chalkAnimation.rainbow(text)
})
```

I think your issue might be running the `logger.log(chalk.green(asciified));` before outputting it to `chalkAnimation`.

![May-12-2021 16-59-09](https://user-images.githubusercontent.com/603949/118049510-76aa8700-b343-11eb-9d7f-b0fbb2373175.gif)

**Comment by nova93** [comment]
@kodie thanks! That works nicely
