### ISSUE TITLE
Bad closing paren

### ISSUE THREAD

**Issue by mp3three** [ajay-gandhi/asciify-image#22]
https://github.com/ajay-gandhi/asciify-image/blob/master/index.js#L137

The height line has it's closing paren in the wrong position, which causes the height argument to not be included as intended
```typescript
return [img.bitmap.width * (opts.height / img.bitmap.height, opts.height)];
```

Should look like this
```typescript
return [img.bitmap.width * (opts.height / img.bitmap.height), opts.height];
```

**Comment by ajay-gandhi** [comment]
Thanks for filing! Resolved and published a new version
