### ISSUE TITLE
Extra wide images don't get resized correctly

### ISSUE THREAD

**Issue by kodie** [ajay-gandhi/asciify-image#5]
When trying to asciify an extra wide image such as this: http://placehold.it/620x140/ff00/00ff using the CLI tool, the image should get resized to fit the terminal, however it doesn't.

My image is 620 pixels wide by 140 pixel high.
My terminal is 125 columns wide by 25 rows high.

My image ends up looking like this:
![screen shot 2018-01-08 at 10 17 17 am](https://user-images.githubusercontent.com/603949/34679964-365431e0-f45d-11e7-85c6-759fd3dc58b7.png)

However, if I set the `c-ratio` to 1, it comes out okay:
![screen shot 2018-01-08 at 10 19 31 am](https://user-images.githubusercontent.com/603949/34680037-74e8eb12-f45d-11e7-97cc-6a0e1f32471c.png)

I'm not really sure why this happens and I'm going to do some more digging to see if I can come up with a solution but I figured I would document it on here.

**Comment by kodie** [comment]
And now that I think about it, even with `c-ratio` set to 1, I don't think that's exactly how the image should be displayed. We should end up with a short image that is as wide as the terminal.

**Comment by kodie** [comment]
It seems like I also get similar results with [image-to-ascii](https://www.npmjs.com/package/image-to-ascii)

**Comment by ajay-gandhi** [comment]
@kodie My first thought is that this might be because each character is taller than it is wide; the "pixels" aren't exactly square in the terminal. I can investigate as well later today.

**Comment by kodie** [comment]
@ajay-gandhi Just pinging you to see if you saw my pull-request (#6) that takes care of this issue.

**Comment by ajay-gandhi** [comment]
Yup I noticed it, should have some free time this evening or worst case tomorrow to merge and publish 👍

**Comment by kodie** [comment]
Sounds great! Thanks!

**Comment by kodie** [comment]
Fixed with #6
