### ISSUE TITLE
Remove `npm` from dependencies?

### ISSUE THREAD

**Issue by ibgreen** [ajay-gandhi/asciify-image#9]
Hi, I've been using your library to log images under Node.js with good results, very helpful indeed when debugging WebGL related code running in headless mode.

However, a problem with this library is that it lists `npm` as a dependency which while unused, is just too heavy for our app installs. If you could move `npm` to `devDependencies` (or completely remove it from package.json) things would look much better.

https://github.com/ajay-gandhi/asciify-image/blob/master/package.json#L13

**Comment by ajay-gandhi** [comment]
Huh, don't know why `npm` was added to begin with. Will do.
